### ISSUE TITLE
unable to install sdk

### ISSUE THREAD

**Issue by anilpally** [vmware/vsphere-automation-sdk-python#335]
### Describe the bug

$ python3 -m pip --no-cache-dir install --upgrade . --user --extra-index-url file://`pwd`/lib

Processing /home/user/vsphere-automation-sdk-python-8.0.0.0

Collecting lxml>=4.3.0 (from vSphere-Automation-SDK==1.78.0)

  Url 'file:///home/user/vsphere-automation-sdk-python-8.0.0.0/lib/lxml/' is ignored: it is neither a file nor a directory.

User for nexus.abc.com: user

Password:

  Downloading https://nexus.abc.com/repository/pypi-all/packages/lxml/4.9.1/lxml-4.9.1-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (5.6MB)

    100% |████████████████████████████████| 5.6MB 1.3MB/s

Url 'file:///home/user/vsphere-automation-sdk-python-8.0.0.0/lib/pyvmomi/' is ignored: it is neither a file nor a directory.

Requirement already up-to-date: pyVmomi>=6.7 in /home/user/.local/lib/python3.6/site-packages (from vSphere-Automation-SDK==1.78.0)

Collecting vapi-runtime@ file://localhost//tmp/pip-20rzdfmh-build/lib/vapi-runtime/vapi_runtime-2.34.0-py2.py3-none-any.whl (from vSphere-Automation-SDK==1.78.0)

Collecting vapi-client-bindings@ file://localhost//tmp/pip-20rzdfmh-build/lib/vapi-client-bindings/vapi_client_bindings-3.9.0-py2.py3-none-any.whl (from vSphere-Automation-SDK==1.78.0)

  Downloading https://nexus.abc.com/repository/pypi-all/packages/vapi-client-bindings/7.0.0/vapi-client-bindings-7.0.0.tar.gz

    Complete output from command python setup.py egg_info:

    Traceback (most recent call last):

      File "<string>", line 1, in <module>

      File "/tmp/pip-build-z_ngjqc6/vapi-client-bindings/setup.py", line 13, in <module>

        license=read('LICENSE.txt'),

      File "/tmp/pip-build-z_ngjqc6/vapi-client-bindings/setup.py", line 5, in read

        with open(os.path.join(os.path.dirname(__file__), fname)) as fn:

    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-z_ngjqc6/vapi-client-bindings/LICENSE.txt'

### Reproduction steps

1. download vsphere-automation-sdk-python-8.0.0.0.tar.gz
2. un tar vsphere-automation-sdk-python-8.0.0.0.tar.gz
3. python3 -m pip --no-cache-dir install --upgrade . --user --extra-index-url file://`pwd`/lib
...

### Expected behavior

install successfully

**Comment by kunal-pmj** [comment]
This is a documentation bug, Kindly use following command to install the SDK.
`pip install --upgrade git+https://github.com/vmware/vsphere-automation-sdk-python.git`
The same has been addressed in following [commit](https://github.com/vmware/vsphere-automation-sdk-python/pull/336).

**Comment by jobingeo** [comment]
Fixed this in https://github.com/vmware/vsphere-automation-sdk-python/pull/336

**Comment by anilpally** [comment]
Thanks for the response, we dont have internet connectivity to run  pip
install --upgrade git+
https://github.com/vmware/vsphere-automation-sdk-python.git

how can i install without hitting the issue downloading the tar. and
installing it from tar?

**Comment by anilpally** [comment]
I followed the local installation method mentioned in the documentation. It
still fails with the LICENSE.txt error, not sure what I am missing.

***@***.*** vsphere-automation-sdk-python-master]$ pip3 install -U
lib/*/*.whl --user

Processing
./lib/nsx-policy-python-sdk/nsx_policy_python_sdk-4.0.1.0.0-py2.py3-none-any.whl

Processing
./lib/nsx-python-sdk/nsx_python_sdk-4.0.1.0.0-py2.py3-none-any.whl

Processing
./lib/nsx-vmc-aws-integration-python-sdk/nsx_vmc_aws_integration_python_sdk-4.0.1.0.0-py2.py3-none-any.whl

Processing
./lib/nsx-vmc-policy-python-sdk/nsx_vmc_policy_python_sdk-4.0.1.0.0-py2.py3-none-any.whl

Processing
./lib/vapi-client-bindings/vapi_client_bindings-3.9.0-py2.py3-none-any.whl

Processing
./lib/vapi-common-client/vapi_common_client-2.37.0-py2.py3-none-any.whl

Processing ./lib/vapi-runtime/vapi_runtime-2.37.0-py2.py3-none-any.whl

Processing
./lib/vmc-client-bindings/vmc_client_bindings-1.61.0-py2.py3-none-any.whl

Processing
./lib/vmc-draas-client-bindings/vmc_draas_client_bindings-1.20.0-py2.py3-none-any.whl

User for nexus.abc.com <http://nexus.swift.com/>: user

Password:

Collecting setuptools (from vapi-client-bindings==3.9.0)

  Using cached
https://nexus.abc.com/repository/pypi-all/packages/setuptools/59.6.0/setuptools-59.6.0-py3-none-any.whl
<https://nexus.swift.com/repository/pypi-all/packages/setuptools/59.6.0/setuptools-59.6.0-py3-none-any.whl>

Collecting idna<2.9,>=2.5; python_version <= "3.6" (from
vapi-runtime==2.37.0)

  Using cached
https://nexus.abc.com/repository/pypi-all/packages/idna/2.8/idna-2.8-py2.py3-none-any.whl
<https://nexus.swift.com/repository/pypi-all/packages/idna/2.8/idna-2.8-py2.py3-none-any.whl>

Collecting pyOpenSSL==19.1.0; python_version <= "3.6" (from
vapi-runtime==2.37.0)

  Using cached
https://nexus.abc.com/repository/pypi-all/packages/pyopenssl/19.1.0/pyOpenSSL-19.1.0-py2.py3-none-any.whl
<https://nexus.swift.com/repository/pypi-all/packages/pyopenssl/19.1.0/pyOpenSSL-19.1.0-py2.py3-none-any.whl>

Requirement already up-to-date: six>=1.12 in
/home/athangal/.local/lib/python3.6/site-packages (from
vapi-runtime==2.37.0)

Collecting cryptography<3.0,>=2.8; python_version <= "3.6" (from
vapi-runtime==2.37.0)

  Using cached
https://nexus.abc.com/repository/pypi-all/packages/cryptography/2.9.2/cryptography-2.9.2-cp35-abi3-manylinux1_x86_64.whl
<https://nexus.swift.com/repository/pypi-all/packages/cryptography/2.9.2/cryptography-2.9.2-cp35-abi3-manylinux1_x86_64.whl>

Collecting requests==2.21.0; python_version <= "3.6" (from
vapi-runtime==2.37.0)

  Using cached
https://nexus.abc.com/repository/pypi-all/packages/requests/2.21.0/requests-2.21.0-py2.py3-none-any.whl
<https://nexus.swift.com/repository/pypi-all/packages/requests/2.21.0/requests-2.21.0-py2.py3-none-any.whl>

Collecting cffi!=1.11.3,>=1.8 (from cryptography<3.0,>=2.8; python_version
<= "3.6"->vapi-runtime==2.37.0)

  Using cached
https://nexus.abc.com/repository/pypi-all/packages/cffi/1.15.1/cffi-1.15.1-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.whl
<https://nexus.swift.com/repository/pypi-all/packages/cffi/1.15.1/cffi-1.15.1-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.whl>

Requirement already up-to-date: certifi>=2017.4.17 in
/home/athangal/.local/lib/python3.6/site-packages (from requests==2.21.0;
python_version <= "3.6"->vapi-runtime==2.37.0)

Collecting urllib3<1.25,>=1.21.1 (from requests==2.21.0; python_version <=
"3.6"->vapi-runtime==2.37.0)

  Using cached
https://nexus.abc.com/repository/pypi-all/packages/urllib3/1.24.3/urllib3-1.24.3-py2.py3-none-any.whl
<https://nexus.swift.com/repository/pypi-all/packages/urllib3/1.24.3/urllib3-1.24.3-py2.py3-none-any.whl>

Collecting chardet<3.1.0,>=3.0.2 (from requests==2.21.0; python_version <=
"3.6"->vapi-runtime==2.37.0)

  Using cached
https://nexus.abc.com/repository/pypi-all/packages/chardet/3.0.4/chardet-3.0.4-py2.py3-none-any.whl
<https://nexus.swift.com/repository/pypi-all/packages/chardet/3.0.4/chardet-3.0.4-py2.py3-none-any.whl>

Collecting pycparser (from cffi!=1.11.3,>=1.8->cryptography<3.0,>=2.8;
python_version <= "3.6"->vapi-runtime==2.37.0)

  Using cached
https://nexus.abc.com/repository/pypi-all/packages/pycparser/2.21/pycparser-2.21-py2.py3-none-any.whl
<https://nexus.swift.com/repository/pypi-all/packages/pycparser/2.21/pycparser-2.21-py2.py3-none-any.whl>

Installing collected packages: idna, setuptools, pycparser, cffi,
cryptography, pyOpenSSL, urllib3, chardet, requests, vapi-runtime,
vapi-common-client, nsx-policy-python-sdk, nsx-python-sdk,
nsx-vmc-aws-integration-python-sdk, nsx-vmc-policy-python-sdk,
vapi-client-bindings, vmc-client-bindings, vmc-draas-client-bindings

  Found existing installation: idna 3.4

    Uninstalling idna-3.4:

      Successfully uninstalled idna-3.4

  Found existing installation: urllib3 1.26.12

    Uninstalling urllib3-1.26.12:

      Successfully uninstalled urllib3-1.26.12

  Found existing installation: requests 2.27.1

    Uninstalling requests-2.27.1:

      Successfully uninstalled requests-2.27.1

Successfully installed cffi-1.15.1 chardet-3.0.4 cryptography-2.9.2
idna-2.8 nsx-policy-python-sdk-4.0.1.0.0 nsx-python-sdk-4.0.1.0.0
nsx-vmc-aws-integration-python-sdk-4.0.1.0.0
nsx-vmc-policy-python-sdk-4.0.1.0.0 pyOpenSSL-19.1.0 pycparser-2.21
requests-2.21.0 setuptools-59.6.0 urllib3-1.24.3 vapi-client-bindings-3.9.0
vapi-common-client-2.37.0 vapi-runtime-2.37.0 vmc-client-bindings-1.61.0
vmc-draas-client-bindings-1.20.0

***@***.*** vsphere-automation-sdk-python-master]$ pip3 install -U .

Processing
/home/userl/vsphere-automation-sdk-python-master/vsphere-automation-sdk-python-master

/home/user/.local/lib/python3.6/site-packages/setuptools/command/install.py:37:
SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and
pip and other standards-based tools.

  setuptools.SetuptoolsDeprecationWarning,

Collecting lxml>=4.3.0 (from vSphere-Automation-SDK==1.79.0)

User for nexus.abc.com <http://nexus.swift.com/>: user

Password:

  Using cached
https://nexus.abc.com/repository/pypi-all/packages/lxml/4.9.1/lxml-4.9.1-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.whl
<https://nexus.swift.com/repository/pypi-all/packages/lxml/4.9.1/lxml-4.9.1-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.whl>

Requirement already up-to-date: pyVmomi>=6.7 in
/home/user/.local/lib/python3.6/site-packages (from
vSphere-Automation-SDK==1.79.0)

Requirement already up-to-date: vapi-runtime@
file://localhost//tmp/pip-w0pbblf6-build/lib/vapi-runtime/vapi_runtime-2.37.0-py2.py3-none-any.whl
in
/home/user/.local/lib/python3.6/site-packages (from
vSphere-Automation-SDK==1.79.0)

Collecting vapi-client-bindings@
file://localhost//tmp/pip-w0pbblf6-build/lib/vapi-client-bindings/vapi_client_bindings-3.9.0-py2.py3-none-any.whl
(from
vSphere-Automation-SDK==1.79.0)

  Downloading
https://nexus.abc.com/repository/pypi-all/packages/vapi-client-bindings/7.0.0/vapi-client-bindings-7.0.0.tar.gz
<https://nexus.swift.com/repository/pypi-all/packages/vapi-client-bindings/7.0.0/vapi-client-bindings-7.0.0.tar.gz>

    Complete output from command python setup.py egg_info:

    Traceback (most recent call last):

      File "<string>", line 1, in <module>

      File "/tmp/pip-build-6x30upmm/vapi-client-bindings/setup.py", line
13, in <module>

        license=read('LICENSE.txt'),

      File "/tmp/pip-build-6x30upmm/vapi-client-bindings/setup.py", line 5,
in read

        with open(os.path.join(os.path.dirname(__file__), fname)) as fn:

    FileNotFoundError: [Errno 2] No such file or directory:
'/tmp/pip-build-6x30upmm/vapi-client-bindings/LICENSE.txt'



    ----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in
/tmp/pip-build-6x30upmm/vapi-client-bindings/

**Comment by MajorDallas** [comment]
> This is a documentation bug, Kindly use following command to install the SDK. `pip install --upgrade git+https://github.com/vmware/vsphere-automation-sdk-python.git` The same has been addressed in following [commit](https://github.com/vmware/vsphere-automation-sdk-python/pull/336).

Why not just fix the package on PyPI?

**Comment by kunal-pmj** [comment]
Hi @MajorDallas 

We working on bringing automation SDK to PyPI.

Tanks
Kunal

**Comment by arthurzenika** [comment]
@kunal-pmj good news! Would there be an issue where we can follow this issue ?
